function dataKey(name: string) {
  return `data_${name}`;
}

function semanticKey(name: string) {
  return `semantic_${name}`;
}

export const kIjxKeys = {
  data: {
    user: dataKey('user'),
    file: dataKey('file'),
    agentToken: dataKey('agentToken'),
    folder: dataKey('folder'),
    workspace: dataKey('workspace'),
    fileBackendConfig: dataKey('fileBackendConfig'),
    fileBackendMount: dataKey('fileBackendMount'),
    presignedPath: dataKey('presignedPath'),
    permissions: dataKey('permissions'),
    permissionGroup: dataKey('permissionGroup'),
    permissionItem: dataKey('permissionItem'),
    assignedItem: dataKey('assignedItem'),
    tag: dataKey('tag'),
    job: dataKey('job'),
    resolvedMountEntry: dataKey('resolvedMountEntry'),
    appRuntimeState: dataKey('appRuntimeState'),
    collaborationRequest: dataKey('collaborationRequest'),
    usageRecord: dataKey('usageRecord'),
    app: dataKey('app'),
    emailMessage: dataKey('emailMessage'),
    emailBlocklist: dataKey('emailBlocklist'),
    appShard: dataKey('appShard'),
    jobHistory: dataKey('jobHistory'),
    utils: dataKey('utils'),
    script: dataKey('script'),
    filePart: dataKey('filePart'),
  },
  semantic: {
    user: semanticKey('user'),
    file: semanticKey('file'),
    agentToken: semanticKey('agentToken'),
    folder: semanticKey('folder'),
    workspace: semanticKey('workspace'),
    fileBackendConfig: semanticKey('fileBackendConfig'),
    fileBackendMount: semanticKey('fileBackendMount'),
    presignedPath: semanticKey('presignedPath'),
    permissions: semanticKey('permissions'),
    permissionGroup: semanticKey('permissionGroup'),
    permissionItem: semanticKey('permissionItem'),
    assignedItem: semanticKey('assignedItem'),
    tag: semanticKey('tag'),
    job: semanticKey('job'),
    collaborationRequest: semanticKey('collaborationRequest'),
    usageRecord: semanticKey('usageRecord'),
    resolvedMountEntry: semanticKey('resolvedMountEntry'),
    app: semanticKey('app'),
    emailMessage: semanticKey('emailMessage'),
    emailBlocklist: semanticKey('emailBlocklist'),
    appShard: semanticKey('appShard'),
    jobHistory: semanticKey('jobHistory'),
    utils: semanticKey('utils'),
    script: semanticKey('script'),
    filePart: semanticKey('filePart'),
  },
  encryption: 'encryption',
  // config: 'config',
  suppliedConfig: 'suppliedConfig',
  runtimeConfig: 'runtimeConfig',
  runtimeState: 'runtimeState',
  secretsManager: 'secretsManager',
  fileProviderResolver: 'fileProviderResolver',
  asyncLocalStorage: 'asyncLocalStorage',
  session: 'session',
  dbConnection: 'dbConnection',
  email: 'email',
  promises: 'promises',
  locks: 'locks',
  disposables: 'disposables',
  usageLogic: 'usageLogic',
  logger: 'logger',
  shardedRunner: 'shardedRunner',
  serverApp: 'serverApp',
  workerPool: 'workerPool',
  queue: 'queue',
  pubsub: 'pubsub',
  cache: 'cache',
  redlock: 'redlock',
  redis: 'redis',
  ioredis: 'ioredis',
  dset: 'dset',
  usage: 'usage',
};
