import {endpointConstants} from '../constants';

export const kFileBackendConstants = {
  routes: {
    addConfig: `${endpointConstants.apiv1}/fileBackends/addConfig`,
    updateConfig: `${endpointConstants.apiv1}/fileBackends/updateConfig`,
    deleteConfig: `${endpointConstants.apiv1}/fileBackends/deleteConfig`,
    getConfigs: `${endpointConstants.apiv1}/fileBackends/getConfigs`,
    getConfig: `${endpointConstants.apiv1}/fileBackends/getConfig`,
    countConfigs: `${endpointConstants.apiv1}/fileBackends/countConfigs`,

    addMount: `${endpointConstants.apiv1}/fileBackends/addMount`,
    updateMount: `${endpointConstants.apiv1}/fileBackends/updateMount`,
    deleteMount: `${endpointConstants.apiv1}/fileBackends/deleteMount`,
    getMounts: `${endpointConstants.apiv1}/fileBackends/getMounts`,
    getMount: `${endpointConstants.apiv1}/fileBackends/getMount`,
    countMounts: `${endpointConstants.apiv1}/fileBackends/countMounts`,
    resolveMounts: `${endpointConstants.apiv1}/fileBackends/resolveMounts`,
  },
  awsRegions: [
    'us-east-2',
    'us-east-1',
    'us-west-1',
    'us-west-2',
    'af-south-1',
    'ap-east-1',
    'ap-south-2',
    'ap-southeast-3',
    'ap-southeast-4',
    'ap-south-1',
    'ap-northeast-3',
    'ap-northeast-2',
    'ap-southeast-1',
    'ap-southeast-2',
    'ap-northeast-1',
    'ca-central-1',
    'eu-central-1',
    'eu-west-1',
    'eu-west-2',
    'eu-south-1',
    'eu-west-3',
    'eu-south-2',
    'eu-north-1',
    'eu-central-2',
    'il-central-1',
    'me-south-1',
    'me-central-1',
    'sa-east-1',
  ],

  maxFolderAttachedMounts: 20,
};
